name: Daily AI Newsletter

on:
  schedule:
    # Run every weekday at 8:00 AM EST (13:00 UTC)
    - cron: '0 13 * * 1-5'
  workflow_dispatch: # Allow manual triggers

jobs:
  generate-and-send-newsletter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run newsletter generation
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        KIT_API_KEY: ${{ secrets.KIT_API_KEY }}
        WHOP_API_KEY: ${{ secrets.WHOP_API_KEY }}
        WHOP_WEBHOOK_SECRET: ${{ secrets.WHOP_WEBHOOK_SECRET }}
      run: |
        cd src
        python main.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: newsletter-logs
        path: src/newsletter.log
        retention-days: 7
